export const UPDATE_MY_CVS = 'UPDATE_MY_CVS';
export const ADD_MY_CV = 'ADD_MY_CV';
export const DELETE_MY_CV = 'DELETE_MY_CV';
export const UPDATE_SELECTED_CV = 'UPDATE_SELECTED_CV';
export const UPDATE_MY_CV = 'UPDATE_MY_CV';
export const SET_LOADING_CV = 'SET_LOADING_CV';
export const SET_ERROR_CV = 'SET_ERROR_CV';
export const ENABLE_SHOW_ERROR_CV = 'EABLE_SHOW_ERROR_CV';
export const DISABLE_SHOW_ERROR_CV = 'DISABLE_SHOW_ERROR_CV';
export const CV_RESPONSE_SUCCESS = 'CV_RESPONSE_SUCCESS';
export const CV_RESPONSE_FAIL = 'CV_RESPONSE_FAIL';

export const UPDATE_MY_COVERS = 'UPDATE_MY_COVERS';
export const ADD_MY_COVER = 'ADD_MY_COVER';
export const DELETE_MY_COVER = 'DELETE_MY_COVER';
export const UPDATE_MY_COVER = 'EDIT_MY_COVER';
export const SET_LOADING_COVER = 'SET_LOADING_COVER';
export const SET_ERROR_COVER = 'SET_ERROR_COVER';
export const ENABLE_SHOW_ERROR_COVER = 'EABLE_SHOW_ERROR_COVER';
export const DISABLE_SHOW_ERROR_COVER = 'DISABLE_SHOW_ERROR_COVER';
export const COVER_RESPONSE_SUCCESS = 'COVER_RESPONSE_SUCCESS';
export const COVER_RESPONSE_FAIL = 'COVER_RESPONSE_FAIL';

export const UPDATE_MY_TEMPLATES = 'UPDATE_MY_TEMPLATES';
export const ADD_MY_TEMPLATE = 'ADD_MY_TEMPLATE';
export const UPDATE_MY_TEMPLATE = 'UPDATE_MY_TEMPLATE';
export const DELETE_MY_TEMPLATE = 'DELETE_MY_TEMPLATE';
export const SET_LOADING_TEMPLATE = 'SET_LOADING_TEMPLATE';
export const SET_ERROR_TEMPLATE = 'SET_ERROR_TEMPLATE';
export const ENABLE_SHOW_ERROR_TEMPLATE = 'EABLE_SHOW_ERROR_TEMPLATE';
export const DISABLE_SHOW_ERROR_TEMPLATE = 'DISABLE_SHOW_ERROR_TEMPLATE';
export const TEMPLATE_RESPONSE_SUCCESS = 'TEMPLATE_RESPONSE_SUCCESS';
export const TEMPLATE_RESPONSE_FAIL = 'TEMPLATE_RESPONSE_FAIL';

export const SEND_EMAIL = 'SEND_EMAIL';
export const SET_EMAIL_CV = 'SET_EMAIL_CV';
export const SET_EMAIL_COVER = 'SET_EMAIL_COVER';
export const SET_ERROR_EMAIL = 'SET_ERROR_EMAIL';
export const SET_SENDED = 'SET_SENDED';

export const OPEN_SIDE_PANEL = 'OPEN_SIDE_PANEL';
export const CLOSE_SIDE_PANEL = 'CLOSE_SIDE_PANEL';
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SET_ERROR_LOGIN = 'SET_ERROR_LOGIN';
export const SET_ERROR_SIGNUP = 'SET_ERROR_SIGNUP';
export const SET_ERROR_USER = 'SET_ERROR_USER';
export const ENABLE_SHOW_ERROR = 'ENABLE_SHOW_ERROR';
export const DISABLE_SHOW_ERROR = 'DISABLE_SHOW_ERROR';
