export const UPDATE_MY_CVS = 'UPDATE_MY_CVS';
export const ADD_MY_CV = 'ADD_MY_CV';
export const DELETE_MY_CV = 'DELETE_MY_CV';
export const UPDATE_SELECTED_CV = 'UPDATE_SELECTED_CV';
export const UPDATE_MY_CV = 'UPDATE_MY_CV';
export const SET_LOADING_CV = 'SET_LOADING_CV';

export const UPDATE_MY_COVERS = 'UPDATE_MY_COVERS';
export const ADD_MY_COVER = 'ADD_MY_COVER';
export const DELETE_MY_COVER = 'DELETE_MY_COVER';
export const UPDATE_MY_COVER = 'EDIT_MY_COVER';
export const SET_LOADING_COVER = 'SET_LOADING_COVER';

export const UPDATE_MY_TEMPLATES = 'UPDATE_MY_TEMPLATES';
export const ADD_MY_TEMPLATE = 'ADD_MY_TEMPLATE';
export const UPDATE_MY_TEMPLATE = 'UPDATE_MY_TEMPLATE';
export const DELETE_MY_TEMPLATE = 'DELETE_MY_TEMPLATE';
export const SET_LOADING_TEMPLATE = 'SET_LOADING_TEMPLATE';

export const OPEN_SIDE_PANEL = 'OPEN_SIDE_PANEL';
export const CLOSE_SIDE_PANEL = 'CLOSE_SIDE_PANEL';
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
